<?php

$words = array(
	'/abstract\b/i', '/else\b/i', '/id\b/i',
	'/instanceof\b/i', '/super\b/i', '/&#x2F/',
	'/boolean\b/i', '/enum\b/i', '/from\b/i',
	'/int\b/i', '/switch\b/i', '/union\b/i',
	'/break\b/i', '/export\b/i', '/select\b/i',
	'/interface\b/i', '/synchronized\b/i',
	'/byte\b/i', '/extends\b/i', '/request\b/i',
	'/let\b/i', '/this\b/i', '/ng\b/i', '/where\b/i',
	'/case\b/i', '/long\b/i', '/\$/', '/delete/i',
	'/throw\b/i', '/catch\b/i', '/javascript/i',
	'/final\b/i', '/native\b/i', '/update/i',
	'/throws\b/i', '/char\b/i', '/{/', '/}/',
	'/finally\b/i', '/new\b/i', '/html\b/i',
	'/transient\b/i', '/class\b/i', '/xml\b/i',
	'/float\b/i', '/null\b/i', '/create\b/i', '/Code\b/i',
	'/const\b/i', '/for\b/i', '/\:\/\//', '/html/i',
	'/package\b/i', '/try\b/i', '/\//', '/parentNode\b/i',
	'/continue\b/i', '/function\b/i', '/getElementsByTagName\b/i',
	'/private\b/i', '/typeof\b/i', '/insertBefore\b/i',
	'/debugger\b/i', '/goto\b/i', '/allow\b/i',
	'/protected\b/i', '/var\b/i', '/position\b/i',
	'/default\b/i', '/if\b/i', '/xss\b/i',
	'/public\b/i', '/void\b/i', '/php\b/i',
	'/delete\b/i', '/implements\b/i', '/insert\b/i',
	'/return\b/i', '/volatile\b/i', '/deny\b/i',
	'/import\b/i', '/getElementById\b/i',
	'/while\b/i', '/double\b/i', '/scroll\b/i',
	'/alert\b/i', '/frames\b/i', '/index\b/i',
	'/outerHeight\b/i', '/#/', '/&amp;/i',
	'/frameRate\b/i', '/outerWidth\b/i',
	'/anchor\b/i', '/function/i', '/&/',
	'/packages\b/i', '/anchors\b/i',
	'/getClass\b/i', '/pageXOffset\b/i',
	'/area\b/i', '/hasOwnProperty\b/i',
	'/pageYOffset\b/i', '/Array\b/i',
	'/parseFloat\b/i', '/blur\b/i',
	'/image\b/i', '/parseInt\b/i', '/</', '/>/',
	'/button\b/i', '/images\b/i', '/init\b/i',
	'/Infinity\b/i', '/pkcs11\b/i',
	'/clearInterval\b/i', '/isFinite\b/i',
	'/plugin\b/i', '/clearTimeout\b/i',
	'/isNaN\b/i', '/prompt\b/i', '/iframe\b/i',
	'/clientInformation\b/i', '/isPrototypeOf\b/i',
	'/propertyIsEnum\b/i', '/close\b/i',
	'/java\b/i', '/prototype\b/i', '/length\b/i',
	'/JavaArray\b/i', '/JavaClass\b/i',
	'/reset\b/i', '/JavaObject\b/i', '/count\b/i',
	'/screenX\b/i', '/crypto\b/i', '/node\b/i',
	'/JavaPackage\b/i', '/screenY\b/i',
	'/innerHeight\b/i', '/scroll\b/i', '/substring\b/i',
	'/decodeURI\b/i', '/innerWidth\b/i', '/str\b/i',
	'/decodeURIComponent\b/i',
	'/layer\b/i', '/select\b/i', '/createElement\b/i',
	'/defaultStatus\b/i', '/layers\b/i',
	'/self\b/i', '/document\b/i', '/img\b/i',
	'/length\b/i', '/setInterval\b/i', '/add\b/i',
	'/element\b/i', '/link\b/i', '/trigger\b/i',
	'/setTimeout\b/i', '/elements\b/i',
	'/location\b/i', '/status\b/i', '/remove\b/i',
	'/embed\b/i', '/Math\b/i', '/body\b/i',
	'/String\b/i', '/embeds\b/i', '/%/',
	'/mimeTypes\b/i', '/submit\b/i', '/head\b/i',
	'/encodeURI\b/i', '/name\b/i', '/\b\?/',
	'/encodeURIComponent\b/i', '/\+/',
	'/NaN\b/i', '/escape\b/i', '/Child\b/i',
	'/navigate\b/i', '/textarea\b/i', '/send\b/i',
	'/eval\b/i', '/navigator\b/i', '/base64\b/i',
	'/top\b/i', '/event\b/i', '/src\b/i', '/client\b/i',
	'/Number\b/i', '/toString\b/i', '/test\b/i',
	'/fileUpload\b/i', '/Object\b/i', '/action\b/i',
	'/undefined\b/i', '/focus\b/i', '/uri\b/i',
	'/offscreenBuffering\b/i', '/unescape\b/i',
	'/form\b/i', '/open\b/i', '/=/', '/filter\b/i',
	'/untaint\b/i', '/forms\b/i', '/getsByTag\b/i',
	'/opener\b/i', '/valueOf\b/i', '/origin\b/i',
	'/frame\b/i', '/option\b/i', '/fromCode\b/i',
	'/window\b/i', '/onbeforeunload\b/i',
	'/ondragdrop\b/i', '/onkeyup\b/i',
	'/onmouseover\b/i', '/onblur\b/i',
	'/onerror\b/i', '/onload\b/i', '/trim\b/i',
	'/onmouseup\b/i', '/ondragdrop\b/i',
	'/onfocus\b/i', '/onmousedown\b/i',
	'/onreset\b/i', '/onclick\b/i',
	'/onkeydown\b/i', '/onmousemove\b/i',
	'/onsubmit\b/i', '/oncontextmenu\b/i',
	'/onkeypress\b/i', '/onmouseout\b/i',
	'/onunload\b/i', '/session\b/i',
	'/cookie\b/i', '/append\b/i', '/FSCommand/i',
	'/appendChild\b/i', '/http/i',
	'/https/i', '/www\b/i', '/seekSegmentTime/i',
	'/js\b/i', '/css\b/i', '/script\b/i'
);